Task/update qa handbook
medigoid/tech-handbook pull request #8
Opened 2022-04-05 03:28 UTC by rendypratama8

adding sub QA workflow
update sub Manual test, E2E automation test, bug report procecdure

2022-04-05 07:01 UTC, aqidd requested changes

2022-04-05 07:01 UTC, aqidd commented on quality-assurance.md
> +Bacaan tambahan ( gunakan akun Medigo untuk akses Udemy *course* ) :
Klinik Pintar harusnya, bukan Medigo

2022-04-05 07:01 UTC, aqidd commented on quality-assurance.md
> +- [Panduan Penggunaan Fabric](https://github.com/medigoid/tech-handbook/blob/develop/fabric-guide.md)
ini apus aja gpp sih

2022-04-05 07:01 UTC, aqidd commented on quality-assurance.md
> -### Dokumen *User Manual*
User manual ga mau dibikin standar? Atau user documentation? Mungkin release notes?

2022-04-06 03:43 UTC, rendypratama8 commented on quality-assurance.md
> +Bacaan tambahan ( gunakan akun Medigo untuk akses Udemy *course* ) :
sudah diupdate

2022-04-06 03:44 UTC, rendypratama8 commented on quality-assurance.md
> +- [Panduan Penggunaan Fabric](https://github.com/medigoid/tech-handbook/blob/develop/fabric-guide.md)
sudah dihapus

2022-04-06 03:44 UTC, rendypratama8 commented on quality-assurance.md
> -### Dokumen *User Manual*
sudah ditambahkan sub release notes

2022-04-07 02:24 UTC, merged